# Site settings
title: this is a test site
email: your-email@domain.com
description: a test site

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
